packages:
  - "."

confirmModulesPurge: false
verifyDepsBeforeRun: false

allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@uiw/codemirror-extensions-basic-setup@4.25.10'
  - '@uiw/react-codemirror@4.25.10'
  - '@codemirror/view@6.43.8'
