"use client";

import { Button, TextArea } from "@heroui/react";
import { useMemo, useState } from "react";
import { BiBot, BiLinkExternal, BiRefresh, BiSend, BiX } from "react-icons/bi";

interface Message { role: "user" | "assistant"; content: string; }

export function AdminAiAssistant({ items, currentLabel }: { items: Array<{ key: string; label: string; desc: string }>; currentLabel: string }) {
	const [open, setOpen] = useState(false);
	const [input, setInput] = useState("");
	const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "你好，我可以帮你查找后台功能、说明配置位置，也可以根据当前页面回答操作问题。" }]);
	const [loading, setLoading] = useState(false);
	const matches = useMemo(() => { const query = input.trim().toLowerCase(); return query ? items.filter((item) => `${item.label} ${item.desc}`.toLowerCase().includes(query)).slice(0, 5) : []; }, [input, items]);
	const send = async () => { const message = input.trim(); if (!message || loading) return; setInput(""); setMessages((current) => [...current, { role: "user", content: message }]); setLoading(true); try { const response = await fetch("/api/ai-chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: `你正在 Go Nav 管理后台。当前页面是“${currentLabel}”。后台功能清单：${items.map((item) => `${item.label}(${item.key})：${item.desc}`).join("；")}。请回答用户问题；如果涉及功能位置，请给出 /admin/{key} 路径。用户问题：${message}`, pageText: document.body.innerText.slice(0, 12000) }) }); const data = await response.json() as { answer?: string; error?: string }; if (!response.ok) throw new Error(data.error || "请求失败"); setMessages((current) => [...current, { role: "assistant", content: data.answer || "没有返回内容。" }]); } catch (error) { setMessages((current) => [...current, { role: "assistant", content: error instanceof Error ? error.message : "请求失败" }]); } finally { setLoading(false); } };
	return <><div className="fixed bottom-5 right-5 z-50">{open ? <section aria-label="后台 AI 助手" className="mb-3 flex h-[min(620px,calc(100dvh-6rem))] w-[min(420px,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-default-200 bg-background shadow-2xl"><header className="flex items-center justify-between border-b border-default-200 px-4 py-3"><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-xl bg-primary-soft text-primary"><BiBot className="size-5" /></span><div><h2 className="text-sm font-semibold">后台 AI 助手</h2><p className="text-[11px] text-default-500">功能查找与操作说明</p></div></div><div className="flex gap-1"><Button isIconOnly size="sm" variant="tertiary" aria-label="清空对话" onPress={() => setMessages([])}><BiRefresh /></Button><Button isIconOnly size="sm" variant="tertiary" aria-label="关闭助手" onPress={() => setOpen(false)}><BiX /></Button></div></header><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-3">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={message.role === "user" ? "ml-8" : "mr-4"}><div className={`rounded-xl px-3 py-2 text-sm leading-6 ${message.role === "user" ? "bg-primary text-primary-foreground" : "bg-default-100"}`}>{message.content}</div></div>)}{loading ? <div className="mr-4 rounded-xl bg-default-100 px-3 py-2 text-sm text-default-500">正在查找后台功能...</div> : null}{matches.length > 0 ? <div className="space-y-1 rounded-xl border border-default-200 p-2"><p className="px-1 text-xs text-default-500">匹配的后台功能</p>{matches.map((item) => <a key={item.key} href={`/admin/${item.key}`} className="flex items-center justify-between rounded-lg px-2 py-1.5 text-sm hover:bg-default-100"><span><strong>{item.label}</strong><small className="ml-2 text-default-500">{item.desc}</small></span><BiLinkExternal className="shrink-0" /></a>)}</div> : null}</div><div className="flex items-end gap-2 border-t border-default-200 p-3"><TextArea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="例如：在哪里配置首页组件？" rows={2} className="min-w-0 flex-1" /><Button isIconOnly aria-label="发送问题" variant="primary" isDisabled={!input.trim() || loading} onPress={() => void send()}><BiSend /></Button></div></section> : null}<Button isIconOnly size="lg" aria-label={open ? "关闭后台 AI 助手" : "打开后台 AI 助手"} variant="primary" className="rounded-full shadow-lg" onPress={() => setOpen((value) => !value)}><BiBot className="size-6" /></Button></div></>;
}
